kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql
  # this labels are replicaset labels
  labels: 
    app: mysql
    tier: expense
    purpose: deployment
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    # replicaset use these labels to find the pods for creating desired number of replicas
    matchLabels:
      app: mysql
      tier: expense
      purpose: deployment
  # pod template
  template:
    metadata:
      labels:
        app: mysql
        tier: expense
        purpose: deployment
    spec:
      containers:
      - name: mysql
        image: niranjan2505/mysql1.0.0:latest
---
kind: Service
apiVersion: v1
metadata:
  name: mysql
spec: 
  selector: # labels are used as selectors
    app: mysql
    tier: expense
    purpose: deployment
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
